// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kawzqpkdyavqvceaqbhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imthd3pxcGtkeWF2cXZjZWFxYmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDk0MjcsImV4cCI6MjA2NjkyNTQyN30.WSwT5FRf5Ct-YrvOBhtWrhbsBveSoUF5yQmOjXpPufo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});